### ISSUE TITLE
Global option that's not an argument

### ISSUE THREAD

**Issue by joeworkman** [davetron5000/gli#128]
I recently noticed that the default values that get displayed in the help will get the values from the config file. Normally I would think that this is brilliant. However, I have a global setting that is a set of rules. 

```
:rules:
- 
  description: Date Rule
  scope: content
  condition: <date>
- 
  description: Find Francisca anywhere and tag her
  scope: content filename
  condition: Francisc\w+
  tags: <match>
- 
  description: Find American Funds and do things to it
  scope: content 
  condition: American Funds
  tags: retirement
  destination: Personal.dtBase2::/Retirement
  service: devonthinkpro
  title: '<match> Statement <date=%Y-%m>'
```

When the help gets displayed, this shows as one huge data structure. I would love a way to either stop displaying the default for this option or even better, a way to hide this global option as an argument. I think that this situation is a edge case where you only want the setting defined in the config file.

**Comment by davetron5000** [comment]
Closing as old.  Feel free to reopen if you need this.
