### ISSUE TITLE
Pass custom banners to GlobalHelpFormat

### ISSUE THREAD

**Issue by chrisarcand** [davetron5000/gli#165]
It doesn't appear that you can pass custom banners to the global help command. For example, I want there to be a DOCUMENTATION:  <something>   banner added, and there doesn't appear to be a good way to do this. Perhaps the GlobalHelpFormat be changed to handle this?

I'm thinking of Commander's `program :help` usage.

**Comment by davetron5000** [comment]
Kinda solved by examples?  This is old, so re-open if examples doesn't help
