### ISSUE TITLE
:must_match regex returns array

### ISSUE THREAD

**Issue by ghost** [davetron5000/gli#166]
In a subcommand I do this

```
subadd.flag [:mac], :must_match => /^((\h{2}([:-]|$)){6})|(\h{12})$/
```

This matches: 

```
56-4d-eb-df-a6-48
56:4d:eb:df:a6:48
564debdfa648
```

The problem is that when must_match is a regex my options get mangled based on the chunk of the regex being matched. While in some cases that could be useful, its unexpected behavior. I would expect must_match to throw an error if it doesn't match, but otherwise give me the unaltered string. Instead I get:

```
 :mac=>["56-4d-eb-df-a6-48", "56-4d-eb-df-a6-48", "48", "", nil],
 :mac=>["56:4d:eb:df:a6-48", "56:4d:eb:df:a6-48", "48", "", nil],
 :mac=>["564debdfa648", nil, nil, nil, "564debdfa648"],
```

**Comment by davetron5000** [comment]
Closing as old.  Since this is just a passthrough to `OptionParse` could be tricky to implement
