### ISSUE TITLE
Support in process running/debugging with aruba

### ISSUE THREAD

**Issue by diabolo** [davetron5000/gli#167]
When you create a new cli app with GLI it would be great if it could support in process running with aruba [see here](1). Perhaps there could be an additional flag to the generator to make this work.

(1) https://github.com/cucumber/aruba#testing-ruby-cli-programs-without-spawning-a-new-ruby-process

**Comment by eterps** [comment]
+1

**Comment by ess** [comment]
So, this sorta works, with the caveat that I haven't actually tried this as an in-process Aruba app yet.

https://gist.github.com/ess/1580d3da7f2d4b74f931

**Comment by Saidbek** [comment]
any progress here? currently trying to mock http requests using vcr + webmock + gli + cucumber no luck so far ...(

**Comment by davetron5000** [comment]
I haven't looked into this as I would not run the application in order to test things as described.  I would test any http-type interactions in a unit test.  I realize that could make it hard to run the entire app end-to-end.

Also, the link the OP posted doesn't work any longer—does anyone have an update as to what the request is wanting to be able to do?

**Comment by ess** [comment]
@davetron5000 Effectively, folks are looking for a way to do with GLI apps what is described here for Thor apps: https://github.com/erikhuda/thor/wiki/Integrating-with-Aruba-In-Process-Runs

I ended up rolling my own CLI app library framework thing around this idea, but the gist posted back in 2015 ( https://gist.github.com/ess/1580d3da7f2d4b74f931 ) is pretty nasty, but it's as close as I got to getting things working. There's almost certainly a better way to do that up ... was just spitballing.

I *think* the only additional bit required in that gist to get things *actually* working would be to set `$stdout`, `$stderr`, and `$stdin` to the relevant values passed into `MyApp::Runner` (most likely in the internal app's `pre` and `post` hooks) in that example, but I honestly don't recall at this point.

**Comment by ess** [comment]
@Saidbek I hope you don't mind ... I've thrown down a PR on your football_cli project, and it appears to work (with one minor curiosity).

**Comment by Saidbek** [comment]
@ess thanks! I'll have a look 👍

**Comment by davetron5000** [comment]
aruba has been removed from this app in favor of integration tests that run the app directly.
