### ISSUE TITLE
Add ability to define different config files for dev and production

### ISSUE THREAD

**Issue by alanwsmith** [davetron5000/gli#172]
I agree with the advice in "Build Awesome Command-Line Applications in Ruby" about placing config files in a user's home directory. Doing so is great but adds one complication to development. Without additional logic, using:

```
config_file File.join(ENV['HOME'], ".app_config.yml")
```

means that both the development and production versions of the script will be using the same config file. When using Cucumber or another testing tool, it's easy to overwrite `ENV['HOME']`, but sometimes it's helpful to run the development version of the app directly from the command line. 

Two solutions I can think of are:
1. Add a new _config_file_for_dev_ method that would be used in conjunction with _config_file_. If the file defined in _config_file_for_dev_ exists, use it. Otherwise, use the file defined in _config_file_ as normal.
2. Update _config_file_ to have the optional ability to accept a hash with keys for dev and prod. Again, if the dev file exists, it's used. Otherwise, the prod file is. 

The more I think about it, the more I like the first option. Especially since it doesn't add a new interface to "config_file" so there's less potential problems with backwards compatibility.

---

Incidentally, the way I'm solving this now is to do the following in my _bin/app_name_ file:

```
executable_directory = File.expand_path(File.dirname(__FILE__))
config_path_for_dev = File.join(File.dirname(executable_directory), 'config_for_dev.yml')
config_path_for_prod = File.join(ENV['HOME'], "#{GLI::App::exe_name}.yml")

if File.exists? config_path_for_dev
  config_file config_path_for_dev
else
  config_file config_path_for_prod
end
```

In the apps development location, I put a "config_for_dev.yml" file at the root. When running `bundle exec bin/app_name`, its found and used. When I use gem to deploy the tool, it uses the config file from the home directory. I've only done a little testing with this, but so far this seems to work fine. (Note that when using Cucumber, etc... they will see the and use the "config_for_dev.yml" file too. I don't think this is ideal, but it allows separation between dev and prod.)

**Comment by rchady** [comment]
An option I would prefer instead would be allow you to pass in a global option to specify the config file to use.  This would be trivial to do if the _config_file_ command would support a lambda, or something else that would allow it to be expanded at runtime vs. a hardcoded string.

**Comment by rchady** [comment]
FYI, this was trivial to add in.  I patched this in to my application, but am providing it here in case you want to add it in to gli itself.

lib/gli/commands/initconfig.rb:

```
action do |global_options,options,arguments|
+         unless global_options[:config].nil?
+           @filename = global_options[:config]
+         end
          if options[:force] || !File.exist?(@filename)
```

This allows everything to work as you would expect.  If you don't specify -c|--config, then the value passed in is used.  If -c|--config are used, then it uses that.

**Comment by davetron5000** [comment]
Consolidated into #305
