### ISSUE TITLE
allow pre/post/around for within the command block

### ISSUE THREAD

**Issue by spazm** [davetron5000/gli#175]
### Motivation:

I'm building a CLI to bundle several related apps into one controller.  I could greatly simplify the logic for each command by wrapping its subcommands with an `around` command.  Using one `around` for all the commands is going to be quite a bit messier.
### Description:

pre/post/around for subcommands would be nested with any higher level pre/post/around.  The `code` structure given to the outermost `around` would run the inner wrapper of the next level in.

```
# triggered first
around do |global_options,command,options,arguments,code|
  File.open(global_options[:filename],'w') do |file|
    options[:file] = file
    code.call   # executes c.around
  end
end

command :foo do |c|
  # triggered by the call to code.call in around
  # triggered for an :foo command or :foo :bar subcommand
  c.around do |global_options,command,options,arguments,code|
    File.open(global_options[:filename2],'w') do |file|
      options[:file2] = file
      code.call  # executes the actual code.  Has access to both :file1 and :file2
    end
  end
end
```

**Comment by davetron5000** [comment]
closing as old.  Re-open if you still need this
