### ISSUE TITLE
Separately passing global_options first

### ISSUE THREAD

**Issue by maltestien** [davetron5000/gli#178]
Hi. I am not sure whether this is the right place to ask this. It's not exactly an issue, more a question. My application saves a lot of configuration in a directory; a lot of that configuration determines which commands are available and which ones are not. Actually, this is a stark simplification, in fact I build a lot of my commands on-the-fly depending on the content of that directory.

I need to implement a global option to allow the user to tell my app where to look for the config directory, like so

```
ruby foo.rb --config-dir ~/.foorc somecommand --somoption etc...
```

My problem is that this puts me in a catch-22. I need to parse the command-line first to figure out which commands to create, but I need to create my commands before I can parse the command-line. When using the pre-block all the parsing of the command-line has already happened, so at this point it's too late to dynamically create my commands and associated options.

Ideally, I would parse all global options first, then build my commands (and associated options, flags, etc.). So, can this be done? I had a good look through the wiki and the API and nothing jumps at me. If you could please nudge me in the right direction, that'd be awesome. Thank you.

**Comment by hyperbolist** [comment]
Here's a solution I've come up with for handling this.

I've added a `--profile` global option to my gli app definition so that it appears in help messages, but I let a bare `OptionParser` instance pick it up so that I can set the appropriate `config_file` right before `exit run(ARGV)`.

Something like this might work for you as well.

    CONFIG_FILE = '.twiliorc'
    # protect ARGV from the destructive power of OptionParser#parse!
    args = ARGV.dup
    # sniff the args for --profile and set the config file accordingly
    @profile = 'default'
    require 'optparse'
    OptionParser::Officious.delete('help') # remove OptionParser's built-in --help listener
    OptionParser::Officious.delete('version') # remove OptionParser's built-in --version listener
    begin
      OptionParser.new do |parser|
        parser.on('--profile [PROFILE]') do |profile|
          @profile = profile
        end
      end.parse!
    rescue OptionParser::InvalidOption
      # no-op, since gli is going to take over now
    end

    if @profile.eql?('default')
      config_file CONFIG_FILE
    else
      config_file "#{CONFIG_FILE}-#{@profile}"
    end

    exit run(args)

**Comment by davetron5000** [comment]
CLosing as old.  Note that #305 exists to capture `initconfig` failings + `commands_from` may help with this issue.
