### ISSUE TITLE
Provide a way to organize commands when there are many of them (i.e. "Don't be curl")

### ISSUE THREAD

**Issue by severen** [davetron5000/gli#192]
I would like for the ability for commands to be hidden from the generated help page, but still be accessed in the usual ways. (appname help command & appname command). Please excuse me if this is already implemented.

**Comment by binford2k** [comment]
@calestar what happened with https://github.com/calestar/gli/compare/gli-2...calestar:help_categories? Are you planning to contribute it?

**Comment by calestar** [comment]
Wow ... I have no idea what happened to that ... did not remember that I had started this ... makes me sad :-(
I'll check quickly tonight ... but the branch is a _little_ bit stale: `This branch is 1 commit ahead, 113 commits behind davetron5000:gli-2`

**Comment by davetron5000** [comment]
I don't *think* I've changed the help code much so maybe it'll just be a fast forward?

**Comment by davetron5000** [comment]
whoa, I just realized how old this issue is.  6 years!  Still, happy to check out a revised PR.  I haven't made many changes to GLI in a while, but I'm still keeping an eye on this repo.

**Comment by calestar** [comment]
Looks like I don't have a Linux machine to test, and WSL gives me weird errors:
```
test_initconfig_permissions(TC_testGLI) [/mnt/d/repos/me/gli/test/tc_gli.rb:267]:
Expected /0600$/ to match "100777".
```
I'll try to resuscitate one of my raspberrypi to continue working on this

**Comment by davetron5000** [comment]
Weird.  I don't have a windows machine to try this on, but that test is making sure the config is not group or world readable, so maybe there is a better way to test that?

**Comment by calestar** [comment]
So the issue with WSL is that when running under a directory that has Windows ACL (`/mnt/[cde...]`)  linux ACLs are not taken into account. So `chmod` does nothing.
Moved my repository to a `real` linux directory in WSL and it works well.
Source: https://github.com/microsoft/WSL/issues/81#issuecomment-207551098

**Comment by davetron5000** [comment]
The GLI test suite has changed with #305   Still up for this, but closing for now as I'm not personally planning on implementing.  Feel free to reopen or make a PR if you have something!
