### ISSUE TITLE
`binding.pry` does not work after including GLI

### ISSUE THREAD

**Issue by smackesey** [davetron5000/gli#196]
```
#!/usr/bin/env ruby
require 'gli'
require 'pry'
include GLI::App
binding.pry
```

Gives error:

> before_session hook failed: NoMethodError: undefined method `process_line' for #<Hash:0x007faf1b22e0d0>
> /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:448:in`run_command'
### Versions

`ruby` : 2.1.1p76
`pry` : 0.10.1
`gli`: 2.12.2

**Comment by simpsora** [comment]
I ran into this issue today, when using GLI 2.13.0 and `aws-sdk` v2:

```
$ bundle exec irb
irb(main):001:0> require 'gli'
=> true
irb(main):002:0> include GLI::App
=> Object
irb(main):003:0> require 'aws-sdk'
=> true
irb(main):004:0> Aws::EC2::Client.new
Aws::Resources::Errors::DefinitionError: unable to define method #accept, method already exists
	from /opt/rubies/2.1.5/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.29/lib/aws-sdk-resources/operation_methods.rb:72:in `safe_define_method'
	from /opt/rubies/2.1.5/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.29/lib/aws-sdk-resources/operation_methods.rb:18:in `add_operation'
	from /opt/rubies/2.1.5/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.29/lib/aws-sdk-resources/definition.rb:92:in `block in define_actions'
	...
```

I'm able to work around this by wrapping my gli app in a module as described above, but that's not ideal.

The AWS gem appears to be adding the `accept` method some instance of one of its own classes (`#<Aws::Resources::Operations::Operation:0x007fade923c0a0>`) when it fails with the above error.  That implies that GLI has already added `#accept` to that object.

**Comment by mbigras** [comment]
@erniebrodeur is there any downside to wrapping the entire `include GLI::App ... exit run ARGV` in a module? I tried it and I'm able to set `binding.pry`s wherever I want now 👍  but I'm not sure what the other effects would be.

For example:

>So, basically, if you include GLI::App in a module, you are isolated. - @davetron5000 

Can you expand on what we're isolating ourselves from by including  `GLI::App in a module?

**Comment by davetron5000** [comment]
when you just do

```ruby
include SomeModule
```

in a ruby script, it adds all of those methods to the global namespace (effectively).  If another app does this, too, things get weird.

But, if you:

```ruby
module Foo
  include SomeModule
end
```

The method in `SomeModule` are only added inside `Foo` and not globally.  Not sure if that helps…

**Comment by mbigras** [comment]
@davetron5000 that makes sense.

Is there anyone downside to wrapping the `include GLI::App` inside a module so `pry` can work though?

**Comment by davetron5000** [comment]
If it works, then "no" :)

Dave

**Comment by dblock** [comment]
#278 wraps things into a `class` and uses `extend`. Any thoughts whether that's better than a module? Felt that calling `run` within a module was dirty.

**Comment by davetron5000** [comment]
The scaffold no longer makes apps with GLI in the global namespace, so closing (I think #278 fixed this so thanks @dblock!)
