### ISSUE TITLE
Provide way to deprecate commands and options

### ISSUE THREAD

**Issue by kowal** [davetron5000/gli#198]
Currently I can't find any way in DSL to specify that given command (or option) should be considered as deprecated. I mean something like:

``` ruby
desc 'Add new entry'
deprecate 'This will be removed in version 1.3. Please use "create" command instead.'
command :add do |c|
# ..
end

command :list do |c|
  c.desc 'List tasks'
  c.switch :all, deprecated: 'Will be removed in 1.4'
  c.flag :filter, deprecated: 'Will be removed in 2.0. Use --query instead'
end
```

This could alter **help output** and print **warnings** when deprecated commands / flags are being used.

What do you think?

**Comment by davetron5000** [comment]
Closing as old.  Re-open if you still need this.
