### ISSUE TITLE
Auto-generate man pages

### ISSUE THREAD

**Issue by IRLeif** [davetron5000/gli#200]
Excerpt from "[Build Awesome Command-Line Applications in Ruby](https://pragprog.com/book/dccar2/build-awesome-command-line-applications-in-ruby-2)" (page 51):

> Unfortunately, neither OptionParser nor GLI provide a way to autogenerate a man page so that your documentation can automatically be kept consistent. Perhaps you’ll be inspired and create such a system.

This sounds like a very useful feature to add and, at the time of writing, I'm feeling inspired.

My skill level is not high enough to implement this feature (yet), but maybe we can get a discussion going on how this could best be implemented? Anyone else interested in this feature?

**Comment by davetron5000** [comment]
Closing as old, though I think this would be a good feature.
