### ISSUE TITLE
allow initconfig to succeed even when required flags are not supplied

### ISSUE THREAD

**Issue by leemhenson** [davetron5000/gli#215]
I have a global required flag that I don't want to be serialized into my config file, which you can think of as being a bit like a account identifier. My users can perform actions across a number of different accounts, and I think it's important that the choice of 'account' is always required as part of the command line args, rather than being provided by the config file. Unfortunately, gli always errors out with `account-id is required` when I attempt to run `initconfig` without providing that flag. I think initconfig should be exempt from rules such as `required` on flags. What do you think?

**Comment by davetron5000** [comment]
Seems reasonable.  I don't think there's a good reason that `initconfig` does validations on the cli arguments—it should just accept anything and allow you to make a config that isn't complete if you want to.

**Comment by davetron5000** [comment]
Consolidated into #305
