### ISSUE TITLE
accept Array isn't working

### ISSUE THREAD

**Issue by edusantana** [davetron5000/gli#219]
I'm trying to make a flag that accepts an array splits at dots (`.`). 

```shell
$ irb
2.2.1 :001 > 'a,b,c.d,e'.split(/,/)
 => ["a", "b", "c.d", "e"] 
2.2.1 :002 > 'a,b,c.d,e'.split(/\./)
 => ["a,b,c", "d,e"] 
```

Then looking at [examples](https://github.com/davetron5000/gli/wiki/Declaring-flags-and-switches#examples) I have written this command to test:

```ruby
command :testarray do |c|
    c.accept Array do |value|
      # puts "it doen't get here"
      value.split(/\./).map(&:strip)
    end
    c.flag :names, :desc => "list of names", :type => Array

    c.action do |global_options,options,args|
        puts options[:names]
    end
end
```

The problem happens when executing it:

```bash
$ bundle exec bin/gliarray testarray --names='a,b,c.d,e'
a
b
c.d
e
```

As you can see it doesn't split as expected. I am doing something wrong?

I'm using gli version `2.13.1`.

**Comment by edusantana** [comment]
With `:type => Hash` it's worse, i have copied it from [lib/gli/app.rb](https://github.com/davetron5000/gli/blob/v2.13.1/lib/gli/app.rb):

```ruby
c.accept(Hash) do |value|
  #puts "--- hash ---"
  result = {}
  value.split(/,/) do |pair|
    k,v = pair.split(/:/)
    result[k] = v
  end
  result
end
c.flag :siglas, :desc => "list of siglas", :type => Hash
```

And the output:

```bash
$ bundle exec bin/gliarray testarray --siglas="a:xxx,b:yyy"
error: unsupported argument type: Hash
$ bundle exec bin/gliarray testarray
error: unsupported argument type: Hash
```

**Comment by davetron5000** [comment]
I think that `accept` might need to be global, i.e. try

```ruby
accept(Hash) do |value|
  #puts "--- hash ---"
  result = {}
  value.split(/,/) do |pair|
    k,v = pair.split(/:/)
    result[k] = v
  end
  result
end
```

before any of your `command` calls. (sorry, not in a position to verify this right now)

**Comment by edusantana** [comment]
YES! That's it!

I will update the wiki to add a note and the comment inside the code.

The code was missing a `each` (`  value.split(/,/).each do |pair|`):

```ruby
accept(Hash) do |value|
  puts "--- hash ---"
  result = {}
  value.split(/,/).each do |pair|
    k,v = pair.split(/:/)
    result[k] = v
  end
  result
end
```

**Comment by edusantana** [comment]
@davetron5000 thanks for the replay. 
I have edited the wiki and did a pull request with comments.
