### ISSUE TITLE
`File.exists?` is deprecated use `File.exist?` instead

### ISSUE THREAD

**Issue by edusantana** [davetron5000/gli#228]
When I run, at debug mode, one app that uses gli, I get this message:

```
/home/eduardo/.rvm/gems/ruby-2.2.1/gems/gli-2.13.3/lib/gli/terminal.rb:46: warning: File.exists? is a deprecated name, use File.exist? instead
```

It's an easy fix, just to replace all theses calls.

**Comment by davetron5000** [comment]
Does `File.exist?` work in Ruby 1.9 and 1.8?

**Comment by edusantana** [comment]
`exist?` exists in 1.8.7: http://ruby-doc.org/core-1.8.7/File.html#method-c-exist-3F
