### ISSUE TITLE
must_match hash

### ISSUE THREAD

**Issue by Manther** [davetron5000/gli#230]
Trying to take advantage of the must_match hash functionality

```
flag 'log-level',
     :type          => String,
     :desc          => 'Log verbosity with actions [d | debug], [i | info], [w | warn], [e | error], [f | fatal], [q | quiet]',
     :required      => false,
     :must_match    => {:d => 0, :debug => 0, :i => 1, :info => 1, :w => 2, :warn => 2, :e => 3, :error => 3, :f => 4, :fatal => 4, :q => nil, :quiet => nil},
     :default_value => :e
```

But I'm getting the key as the value in global instead of the value. 

ie global['log-level']  # = :e not 3

**Comment by davetron5000** [comment]
This isn't an intended use of `must_match`.  the intention is that you give it a regexp.

The reason this works and why it's doing this is that GLI is sending that value to the underlying OptionParser, but I don't know if GLI is actually using it to extract the value.  You might want to look at `accept` to do this instead.

**Comment by Manther** [comment]
Ok thank you. I was going off the examples in the wiki. What is this example talking about?

"If it's a Hash, the argument's value must be a key in that Hash, but the value provided at runtime will be that key's value."
```
flag :environment, :must_match => { "production"  => :prod,
                                    "staging"     => :stage,
                                    "development" => :dev}
# => --environment=test will fail
# => --environment=development will work and options[:environment] will be :dev
```

**Comment by davetron5000** [comment]
Oh, hm.  you are right, this is the intention.  I totally forgot.  There is even [a test for it](https://github.com/davetron5000/gli/blob/gli-2/test/tc_gli.rb#L366), so I'm not sure why it's not working for you.  Do you have a minimal app you can post that shows this behavior?

**Comment by Manther** [comment]
So I set out to provide you with a simple example, and I found the issue. 
It's that I had the type set to "String" If I just take the type off, it works fine. 

I.E. this works:
flag :environment, :must_match => { "production"  => :prod,
                                    "staging"     => :stage,
                                    "development" => :dev}

This does not work:
flag :environment, :type => String, :must_match => { "production"  => :prod,
                                    "staging"     => :stage,
                                    "development" => :dev}

**Comment by Manther** [comment]
I did notice however that the default value does not evaluate to the value it should 

flag :environment, :must_match => { "production" => :prod,
                                    "staging" => :stage,
                                    "development" => :dev},
     :default_value => "production"

If you let environment go to the default it comes out as global[:environment] # => 'production'
As opposed to 'prod'

**Comment by Manther** [comment]
Sorry one last thing. It doesn't translate to the correct value if pulling it from the config file also.

**Comment by davetron5000** [comment]
ok, I see.  Yeah, this is a function of the fact that it's using `OptionParse` under the covers. 

For the default value stuff, you are saying that the default value is "production", which isn't a valid value.  i.e. the defaults and config will bypass the `must_match` and set directly.  So, it's behaving as intended, it's just a big confusing.

I'm trying to think how this could be improved.  I could see having GLI warn you if your default (or configured) value isn't technically valid.  Or, it could just blow up, too?

**Comment by Manther** [comment]
Yes, for all the the defaults (default_value, and what get parsed out of the config) the 'key's in the must_match hash, and not the values are whats available to you after parsing. So 'production' instead of 'prod'. 

The best improvement obviously would be to make it so that the defaults returned the value of hash items after parsing. But, that may be a ton of work I don't know. The reason why is, if I have to write some method with a switch that translates 'production' to 'prod' ETC for the defaults situation, then I might as well not bother with using this feature: => "If it's a Hash, the argument's value must be a key in that Hash, but the value provided at runtime will be that key's value." Which is a bummer because it's a cool feature.

**Comment by Manther** [comment]
This will work.

```
LOGLEVEL = {:d     => Logger::DEBUG, :debug => Logger::DEBUG,
            :i     => Logger::INFO, :info => Logger::INFO, :w => Logger::WARN,
            :warn  => Logger::WARN, :e => Logger::ERROR, :error => Logger::DEBUG,
            :f     => Logger::FATAL, :fatal => Logger::FATAL, :q => nil,
            :quiet => nil}.freeze

# Global flag to specify the log level
     flag 'log-level',
     :desc          => 'Log verbosity with actions [d | debug], [i | info], [w | warn], [e | error], [f | fatal], [q | quiet]',
     :required      => false,
     :must_match    => [:d, :debug, :i, :info, :w, :warn, :e, :error, :f, :fatal, :q, :quiet],
     :default_value => :error

 @logger.level = LOGLEVEL[global['log-level']]
