### ISSUE TITLE
Can't pass JSON string as an arg. 

### ISSUE THREAD

**Issue by Manther** [davetron5000/gli#231]
When define a String type flag:

```
  c.flag :s, 'input-parameters-string',
         :type     => String,
         :desc     => 'Input parameters string',
         :required => false
```
and pass something in like this:

```
-s '{"username":"xyz","password":"xyz"}'
```
After GLI/optparse parses the arg the inner quotes get stripped off, and the string cannot be parsed as JSON
it looks like this:

```
'{username:xyz,password:xyz}'
```
I have tried many combinations of single quotes and double quotes, but none have resulted in success. 

Here is an example usage of other command line applications accepting json strings as arguments (just for reference of what i'm trying to accomplish):
```
curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:3000/api/login
```
Thank you.

**Comment by davetron5000** [comment]
This is not my experience trying it just now:

```ruby
flag :f, type: String

command :init do |c|

  c.action do |global,options,args|
    puts global[:f]
    puts JSON.parse(global[:f]).inspect
  end

end
```

Then:

```
> my_app -f '{"username":"xyz","password":"xyz"}' init
{"username":"xyz","password":"xyz"}
{"username"=>"xyz", "password"=>"xyz"}
```

Can you post more of your app?

**Comment by Manther** [comment]
Welp, it was a Rubymine thing. I took your exact example and tried it and it was still failing. I was debugging it through Rubymine and the textbox you type the "Script arguments" in must be parsing the string ahead of time. From the command line it works fine. I just hadn't run this exact command sequence from the command line yet. Thank you. Closing.
