### ISSUE TITLE
Not everything works on Windows

### ISSUE THREAD

**Issue by crush-157** [davetron5000/gli#245]
Just starting with gli.  I have created an example app as per the wiki (`$ gli init todo list add complete`).

`$ bundle exec bin/todo` works as expected.

But when I run `$rake cucumber` I get an odd result:

`expected that command "todo help" has exit status of "0", but has "".`

If I check the return code for `$ bundle exec bin/todo help` (using `$echo $?`) then it does return 0.

I'm curious as to why this is happening and would like to understand the issue, just to be sure that there isn't an underlying problem that is going to come back and bite me later.

I am running ruby on Cygwin:

ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-cygwin]

**Comment by davetron5000** [comment]
Sorry for the delay in responding.

I just tried this on OS X and everything works.  I was never able to get any of this stuff working on Windows (in particular, Aruba seemed to completely not work at all on Windows).  Further, I don't have access to a Windows box to try.

On the off chance it's a gem version problem, I did this:

```
> rvm use 2.2@gli-test --create # there's no 2.2.4p230 for OS X, so 2.2.4 is the closest I could get
> gem install gli
> gli init todo list add complete
> cd todo
> bundle install
> bundle exec rake cucumber
..

1 scenario (1 passed)
2 steps (2 passed)
0m0.321s
```

The gems that were installed are:

```
aruba (0.14.1)
bigdecimal (1.2.6)
builder (3.2.2)
bundler (1.12.5)
bundler-unload (1.0.2)
childprocess (0.5.9)
contracts (0.14.0)
cucumber (2.3.3)
cucumber-core (1.4.0)
cucumber-wire (0.0.1)
diff-lcs (1.2.5)
executable-hooks (1.3.2)
ffi (1.9.10)
gem-wrappers (1.2.7)
gherkin (3.2.0)
gli (2.14.0)
io-console (0.4.3)
json (1.8.3, 1.8.1)
multi_json (1.12.1)
multi_test (0.1.2)
psych (2.0.8)
rake (11.1.2, 10.4.2)
rdoc (4.2.2, 4.2.0)
rspec-expectations (3.4.0)
rspec-support (3.4.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
thor (0.19.1)
```

Do yours match?  If you have differences, can you post them and I'll try on my end…

**Comment by crush-157** [comment]
Different gem versions:
  bigdecimal (1.2.7)
  bundler (1.9.9)
  io-console (0.4.2)
  json (1.8.2)
  multi_json (1.11.0)
  psych (2.0.13)
  rake (10.4.2)
  rdoc (4.2.0)

Missing gems:
  bundler-unload
  executable-hooks
  gem-wrappers
  rubygems-bundler
  rvm

**Comment by crush-157** [comment]
I'll see if I can try it on a Linux box this evening.

Downside is I need it to work on Windows :-(

**Comment by crush-157** [comment]
Somewhat later than advertised, I tried the same steps on  a fresh Ubuntu install - and of course it worked just fine :-)

Which is great, except it I (or rather some of my users) will need it to work on Windows :-(

**Comment by davetron5000** [comment]
Closingn as old + I have removed aruba so maybe this does work on Windows? I still don't have a windows box to test on.
