### ISSUE TITLE
Typo on what is a switch?

### ISSUE THREAD

**Issue by ddoherty03** [davetron5000/gli#246]
On the detailed [walk-through](http://naildrivin5.com/gli/), you explain switches as

> Options that don't merely switch something on or off, and are called switches.

It seems you mean the opposite:

> Options that merely switch something on or off are called switches.

Note the deletion of "don't" and ", and".  This confused me when I first read the documents.  I don't know if it appears elsewhere.

**Comment by davetron5000** [comment]
Wow, nice catch.  That has been there for a very long time and I can't believe no one else saw it!

It's now fixed (see 41841157cf58fe4e4833a9590787b243365af27e if you are curious where that website's source is).

Thanks!

**Comment by ddoherty03** [comment]
Dave,

Just catching up on some old messages.  I see that you still have the ", and" in there.  I think you meant that to go as well.  But this is more of a nit than the "don't".  Regards.
