### ISSUE TITLE
Bad `help` command returns zero status code

### ISSUE THREAD

**Issue by JacobEvelyn** [davetron5000/gli#255]
Using the `help` command with a bad argument, e.g. `friends help garbage` gives me this GLI error:

```
error: Unknown command 'garbage'.  Use 'friends help' for a list of commands.
```

But despite this being an error state, the status code returned is 0. Is there a way to make this nonzero?

**Comment by davetron5000** [comment]
There's always a way :)

I'm surprised though, because an unknown command error should exit 1.

There's code to put an unknown command back into the args in case the user is trying to use a default command—maybe that's where it's going wrong?

**Comment by davetron5000** [comment]
Closing as old. Please reopen with a repo example if you are still experiencing this
