### ISSUE TITLE
How to create subcommand for a flag

### ISSUE THREAD

**Issue by KINGSABRI** [davetron5000/gli#271]
Hello guys 
How to create a sub-command for a flag, the subcommand might have command, flags and switches as well
```
# example 1
rubyfu --do-this1 --module MODULENAME --mod-lag --mod-switch 

# example 2
rubyfu --do-this1 --module COMMAND
```

**Comment by davetron5000** [comment]
Each subcommand can have flags—everything nests.  See the [wiki article](https://github.com/davetron5000/gli/wiki/Subcommands) and let me know if that helps.

**Comment by KINGSABRI** [comment]
@davetron5000 thanks for the reply I've checked the wiki. The wiki explains subcommand and sub-subcommand and subcommand's switches and flag. 

However, what I'm looking for is having a flag/switch has commands, these commands have flags/switches

**Comment by davetron5000** [comment]
I'm not sure what you are wanting to do—do you want to execute code whenever someone uses a flag?  If so, you can do that by checking the flag in the command's `action` block.

In general, GLI is based on having flags/switches set options for the command and not to instigate actions themselves.

**Comment by davetron5000** [comment]
Closing as old and I think not an issue?  Please reopen if you have more info
