### ISSUE TITLE
commands_from doesn't respect scope

### ISSUE THREAD

**Issue by dblock** [davetron5000/gli#279]
The implementation of `commands_from` is https://github.com/davetron5000/gli/blob/84c21131320168178077e9bfe03f51f0e28d361e/lib/gli/app.rb#L319 and is a simple `require`. If you call it from a class, it will create global scope, not local to where it was called from.

**Comment by davetron5000** [comment]
I'm not sure how to solve this w/out breaking backwards compat, but you are correct in how it behaves
