### ISSUE TITLE
Mutually Exclusive Options?

### ISSUE THREAD

**Issue by IotaSpencer** [davetron5000/gli#283]
Would there be an easy way for either me or you and myself to implement mutually exclusive options so that either a `default_value: true` can be disabled when using an MEO, or another flag parameter that you list the options that are not to be used with it.

**Comment by davetron5000** [comment]
Can you show an example of what you mean? I'm not 100% sure I follow.

**Comment by IotaSpencer** [comment]
https://github.com/skorks/escort/blob/d0c021b92ea41128807a37854ec5486d0aa7150c/lib/escort/option_parser.rb#L69-L79

https://github.com/skorks/escort/blob/master/lib/escort/option_dependency_validator.rb

https://github.com/skorks/escort/blob/master/lib/escort/trollop.rb#L252-L264

And then https://github.com/skorks/escort#option-dependencies from the anchor down

**Comment by davetron5000** [comment]
Sorry, I still don't understand.  What is the behavior you would like to see? Can you show some command-line invocations of a hypothetical app that had this feature and how that app would behave?

**Comment by IotaSpencer** [comment]
Well first off, either way, I'd want it to be added onto the flag invocation, but something like this out of my project would qualify as a option I don't want to have to do a --no-* on

```shell
$ cloudflare_cli zones list 
```
outputed is a ascii table (code mostly irrelavent to how options are parsed)
(--table is because  `default_value: true`)

```shell
$ cloudflare_cli zones --output 'result.name' --output 'result.status' --output-sep newline
```
which if table was a conflicted option and disabled itself when another conflicting option was used, should only output the following

```shell
ken@kenny:~/everygit/cloudflare_cli$ bundle exec bin/cloudflare_cli zones list \
  --output "result.first.name" \
  --output "result.first.status" \
  --output-sep newline
e-code.in
active
```
If there were a 'depends_on' then I could make --output-sep require at least one --output
```shell
$ cloudflare_cli --output-sep newline
error: flag 'output-sep' requires the option 'output' to be used (in tandem or similar word)
```
*****
Then what was actually used
(--table put in asterisks for clarity)
<pre>
bundle exec bin/cloudflare_cli zones list \
  **--no-table** \
    --output 'result.name' \
    --output 'result.status' \
    --output-sep newline
</pre>

**Comment by IotaSpencer** [comment]
What actually gets outputted is then

```
ken@kenny:~/everygit/cloudflare_cli$ bundle exec bin/cloudflare_cli zones list --output "result.first.name" --output "result.first.status" --output-sep newline
+-----------------------+------------------------------------------------------------------+
|                                          Zones                                           |
+-----------------------+------------------------------------------------------------------+
|                                        e-code.in                                         |
+-----------------------+------------------------------------------------------------------+
.
. table contents
.
+-----------------------+------------------------------------------------------------------+
|                                     electrocode.net                                      |
+-----------------------+------------------------------------------------------------------+
.
. table contents
.
+-----------------------+------------------------------------------------------------------+
|                                      iotaspencer.me                                      |
+-----------------------+------------------------------------------------------------------+
.
. table contents
.
+-----------------------+------------------------------------------------------------------+
| success               | true                                                             |
| errors                | none                                                             |
| messages              | none                                                             |
+-----------------------+------------------------------------------------------------------+
e-code.in
active
```

**Comment by davetron5000** [comment]
OK, so it sounds like you are wanting a few things:

* be able to specify that two options may not be specified together and if so, it's an error.
* If an option has a default, and one of it's mutually exclusive options is set, don't set the default (set `nil`?)
* be able to specify that two options are required together (opposite of mutually exclusive), i.e. if one is given, the other must be given as well.

Much of GLI's option parsing is deferred to the standard Ruby `OptionParser`, so to implement something like this, we'd need to:

* Agree on what the DSL/API is like for the developer
* Write code that happens after all options are parsed that can examine them and generate the requisite errors.
* Probably changes in the help output to indicate options that are mutually exclusive or mutually required are that way

GLI has the concept of a `pre` hook that is given all the parsed options and can decide to execute the command or not, based on what's in there.  That's how you could implement this in your app directly, but I would think to make this a GLI feature, we could have some sort of built-in pre blocks to handle these checks.

**Comment by IotaSpencer** [comment]
Yes, and I can show you what I'm currently having to do to check all this, though I have made the default_value for table currently false so I don't have to deal with that as much

**Comment by IotaSpencer** [comment]
This being from [here](https://github.com/IotaSpencer/cloudflare_cli/blob/develop/lib/cloudflare_cli/commands/005_memberships.rb#L22-L41)
as you can see its a bit cumbersome
and hopefully I can do something like
```ruby
        lm.flag :'output-sep', desc: 'choose character to separate output fields', must_match: [:newline, :crlf, :space], required: false, default_value: :space, depends_on: [:output]
        lm.flag :output, desc: 'output fields, use multiple times to output multiple fields', multiple: true, conflicts_with: [:table, :json
        lm.switch :table, desc: 'Put some of the output into a table', default_value: false, conflicts_with: [:output, :json]
        lm.switch :json, desc: 'output raw json', default_value: false, conflicts_with: [:table, :output]
```
considering output is a multiple value and does exist in the options no matter what, unlike something being nil or not in the hash, this may cause some problems, do to most likely having to check if --output was given rather than just being empty

```ruby
          if options[:json] and options[:table] and options[:output].empty?
            puts js.to_json
          elsif options[:table] and not options[:json] and options[:output].empty?
            table = CloudflareCli::Methods::Tables::Memberships.new('Memberships', js)
            table.make_it_so
            table.beam_me_out
          elsif not options[:output].empty? and options[:'output-sep'] and not options[:table] and not options[:json]
            want = CloudflareCli::Methods::Output.new(options[:output], options, js)
            want.put
          else
            if options[:json] and options[:table]
              raise FlagSwitchConflictError.new('json', 'table')
            end
            if options[:output].empty? and options[:'output-sep']
              raise FlagSwitchDependencyError.new('option-sep', 'output')
            end
          end
```

**Comment by IotaSpencer** [comment]
Well easy stuff first, help output:

```
ken@kenny:~/everygit/cloudflare_cli$ bundle exec bin/cloudflare_cli help memberships list
NAME
    list - list memberships

SYNOPSIS
    cloudflare_cli [global options] memberships list [command options] 

COMMAND OPTIONS
    --direction, --dir=arg - direction to order results (default: asc)
    --[no-]json            - output raw json (conflicts with: --table, --output) # <---
    --order=arg            - field to order memberships by (default: none)
    --output=arg           - output fields, use multiple times to output multiple fields (may be used more than once, default: none, conflicts with: --table, --json) # <---
    --output-sep=arg       - choose character to separate output fields (default: space, depends on: --output) # <---
    --page=arg             - page to query (default: 1)
    --per_page=arg         - how many accounts listed per page (default: 20)
    --[no-]table           - Put some of the output into a table (conflicts with: --json, --output) # <---

**Comment by IotaSpencer** [comment]
something simple like this would also work

https://github.com/ManageIQ/optimist/wiki/Medium-Example#dependencies-and-conflicts

**Comment by davetron5000** [comment]
Closing as old.  Given that it can work with `pre` I hope that is working for you, but please re-open if not
