### ISSUE TITLE
Cannot get `true` to work as a default switch value

### ISSUE THREAD

**Issue by sd-trailhead-james** [davetron5000/gli#286]
Let's say I have a global `:verbose` switch. I want it to have a default value of `true` so that the app operates in verbose mode by default. Users can then specify `--no-verbose` to disable/decrease verbosity.

I have attempted to represent that desired behavior with the following code, but the default value for the switch is `false`. Running the app without the switch results in `false`. Running it with `--verbose` results in `true`, and running it with `--no-verbose` results in `false`. So when the switch is present, the behavior is as desired, but I can't get the default value of `true` to work as desired. How can I get the switch to be `true` by default when the user omits the switch?

```ruby
#!/usr/bin/env ruby

require "gli"

class Test
  extend GLI::App

  desc "A 'verbose' switch defaulting to true"
  switch [:verbose], default: true

  desc "Test command"
  command :test do |c|
    c.action do |global_opts, _opts, _args|
      puts "Verbose mode = #{global_opts[:verbose]}"
      puts
    end
  end
end

puts "default run - expect to receive 'true'"
Test.run(%w(test))  # <-- this one prints 'false' for some reason

puts "run with --verbose - expect to receive 'true'"
Test.run(%w(--verbose test))

puts "run with --no-verbose - expect to receive 'false'"
Test.run(%w(--no-verbose test))
```

**Comment by davetron5000** [comment]
This is a bit confusing, but you have to use `default_value`.  the `switch` command won’t complain about unknown flags, so it happily accepts `default`, even though it’s not recognized.

**Comment by sd-trailhead-james** [comment]
Thanks, @davetron5000! That was indeed all it was.
