### ISSUE TITLE
bundle exec bin/todo breaks in ruby 2.6.5

### ISSUE THREAD

**Issue by axmachina** [davetron5000/gli#293]
Only tested in ruby 2.6.5p114 (2019-10-01 revision 67812)

bundle seems to assume "bin/"

the proper way to run (from app root) 

`bundle exec todo`

**Comment by davetron5000** [comment]
Not sure how I missed this (1 year+++ ago!) but `bundle exec bin/todo` seems to work for me and the integration tests do this and pass on Ruby 2.5 and above.  That said, please re-open if you have more info about what's going wrong.
