### ISSUE TITLE
Discussion: Upgrading Aruba in GLI

### ISSUE THREAD

**Issue by luke-hill** [davetron5000/gli#294]
Hi there,

I was wondering if we could discuss trying to bump the version of `aruba` currently in use in `gli`

Ideally first bumping to `0.8.0` and then to `0.14.9`, from there supporting the latest `0.x` version.

The reason is that we're trying to get all gems which are large and using aruba using a `0.14.x` version where a lot of the bugfix and deprecation PR's are going in. As we're looking to release 1.0 of aruba in the near future.

If you could have a stab or let us know what we can do to help that would be great. It might be that the upgrade works flawlessly, if so that's awesome.

Try `0.8.0` and then `0.14.9` as the first two static upgrades would be my advice. Any other queries ask away I'll try help

Luke

**Comment by davetron5000** [comment]
Hey. Yeah, I have tried this a few times over the years (!).  The main issue is that Aruba seems to have changed how it sets the path for executing commands and for whatever reason it's incompatible with GLI and I could not make it work.  

I just tried to update to 0.8.0 and this is the issue I hit.  I'm sure it's fixable, but I haven't had time to work with it.

**Comment by luke-hill** [comment]
That's fine. If there's a PR or something where I can view failures I can try co-operate e.t.c. Or if you enable me to have push privileges to a branch I can try do something.

Happy to help, just not sure where I need to do whatever

**Comment by davetron5000** [comment]
I have removed aruba in favor of integration tests.  They don't cover as much as the aruba ones but I think they will make it easier to maintain this app with one less dependency.  See #303
