### ISSUE TITLE
Slower computers can't run the tests

### ISSUE THREAD

**Issue by calestar** [davetron5000/gli#296]
Systematically getting a failure on the tests when running from RPi:
```
(::) failed steps (::)

process still alive after 5 seconds (ChildProcess::TimeoutError)
features/gli_init.feature:125:in `When I run `rake test`'

Failing Scenarios:
cucumber features/gli_init.feature:12 # Scenario: Scaffold generates and things look good
```

**Comment by davetron5000** [comment]
I have removed aruba/cucumber from the repo entirely and made integration tests that just shell out to call the app.  That should at least not artificially limit how long things run.  LMK if that works and re-open if not
