### ISSUE TITLE
"requires a subcommand" error without examples

### ISSUE THREAD

**Issue by JacobEvelyn** [davetron5000/gli#298]
I noticed an inconsistency in the help message when using commands that require subcommands. When I call the [`list` command in my `friends` CLI app](https://github.com/JacobEvelyn/friends/blob/master/lib/friends/commands/list.rb#L4), it gives examples:

```
friends list
Error: Command 'list' requires a subcommand friends,activities,notes,locations,tags,favorite
```

but when I use [one of those subcommands that also requires further subcommands](https://github.com/JacobEvelyn/friends/blob/master/lib/friends/commands/list.rb#L94), I see no examples:

```
friends list favorite
Error: Command 'favorite' requires a subcommand
```

Is there a way to get that second example to also show the subcommand options?

**Comment by davetron5000** [comment]
Yeah, that doesn't seem right.

It looks like this line of code:

https://github.com/davetron5000/gli/blob/85792ea395ce72069cbd6190ecaca26dfaea2684/lib/gli/command_support.rb#L173

Should probably include the same thing as this one:

https://github.com/davetron5000/gli/blob/85792ea395ce72069cbd6190ecaca26dfaea2684/lib/gli/command_support.rb#L176

or maybe have the same check?

If you feel like making a PR, I can check it out and .  I might not have bandwidth to do the change myself for the next few weeks or so.

**Comment by JacobEvelyn** [comment]
Thanks, @davetron5000 ! I'll look into making a PR in the next week or so.
