### ISSUE TITLE
How to call a command with another command

### ISSUE THREAD

**Issue by ttscoff** [davetron5000/gli#313]
I dug through the code to try to answer this myself, but haven't quite figured it out yet. I want to call a command with specific flags set from within another command. Is there a method for that?

Basically I want a subcommand that executes another command with a bunch of flags and switches but all preset so that `app command` has the same effect as `app othercommand --flag=val --switch --flag2=val2 --no-switch`, etc.

**Comment by davetron5000** [comment]
an inelgeant way would be to use `exec` which replaces the current process with whatever you give it:

```ruby
exec("#{$0} othercommand --flag=val --switch --flag2=val2 --no-switch")
```

Another option would be to access the object for that command (via the `commands` method that should be available wherever you mixed-in `App` [but note this is hierarchical so you'd have to walk the tree of commands]), and then execute its `action` block:

```ruby
options = {
  flag: val,
  switch: true,
  flag2: val,
  other_switch: false,
}
command.action.(global_options, options,args)
```

A third option would be to store `othercommand`'s `action` block as some global variable or variable somewhere and use that:

```ruby
othercommand_action = ->(global_options, options, args) {
  # whatever the command does
}

command :command do |c|
  options = {
    flag: val,
    switch: true,
    flag2: val,
    other_switch: false,
  }
  c.action do |g,o,a|
    othercommand_action.(g,options,a)
  end
end

command :othercommand do |c|
  c.action do |g,o,a|
    othercommand_action.(g,o,a)
  end
end
```

**Comment by ttscoff** [comment]
Option 2 is exactly what I was hoping for. Will try it out with option 3 as a fallback. Thanks.

**Comment by ttscoff** [comment]
I might actually need a bit more explanation of how to call the action for option 2. My ruby skills are showing their limits.

I can retrieve the command in question using `commands[:tag]`, and printing out the object shows me all of its flags and methods, including `@action` as a Proc. However, `commands[:tag].action.inspect`  is nil, and running `commands[:tag].action.(g, o, a)` gives me an error about calling `call` on nil. Is there some other method by which I need to call the command?

**Comment by ttscoff** [comment]
Works perfectly, thank you.

(Also, GLI is one of my favorite things. Just in general. It's awesome and I'd hate to create CLIs without it. So thank you for the amazing contribution!)

**Comment by davetron5000** [comment]
Awesome and thanks for the kind words!
