### ISSUE TITLE
flags don't aggregate into an array

### ISSUE THREAD

**Issue by yegor256** [davetron5000/gli#320]
Thanks for your library, it's amazing! Now, the problem. I'm doing this:

```
require 'gli'
include GLI::App
command :bar do |c|
  c.flag([:foo], type: Array)
  c.action do |global, options, args|
    p options
  end
end
run(["bar", "--foo", "first", "--foo", "second"])
```

I'm getting (the `--foo first` is lost 👎 ):

```
{"foo"=>["second"], :foo=>["second"]}
```

Instead, I would expect:

```
{"foo"=>["first", "second"], :foo=>["first", "second"]}
```

This is what I'm getting, when I change the last line to:

```
run(["bar", "--foo", "first,second"])
```

I believe, it's a normal practice to pass options in command line by using the same flag multiple times. Joining values with a comma may be a good practice too, but not always suitable.

Maybe I missed some configuration option for this particular behavior?

**Comment by davetron5000** [comment]
There are two ways to do this.  The one that is simplest is to set `multiple: true`:

```ruby
  require 'gli' 
  include GLI::App
  command :bar do |c|
→   c.flag([:foo], multiple: true)
    c.action do |global, options, args|
      p options
    end
  end
  run(["bar", "--foo", "first", "--foo", "second"])
```

That said, what you have should work with comma-delimited arguments, due the use of `type: Array`.  For me,

```
run(["bar", "--foo", "first,second"])

# {"foo"=>["first", "second"], :foo=>["first", "second"]}
```

**Comment by davetron5000** [comment]
Thanks!  Let me know how things go - I haven't been doing many updates as it's generally stable, but I'm still around to support it.

**Comment by yegor256** [comment]
@davetron5000 works perfectly, [here](https://github.com/yegor256/judges/blob/master/bin/judges). If any more issues, I will report :)
