### ISSUE TITLE
Extend using app-command as git allows

### ISSUE THREAD

**Issue by jkm** [davetron5000/gli#68]
What about forwarding unknown commands to `app-command`. git allows this and this is handy because it allows adding your own commands. E.g. `app unknown` should execute `app-unknown`.

**Comment by davetron5000** [comment]
This can be achieved more or less by using `commands_from` to load custom commands not bundled with the app:

https://github.com/davetron5000/gli/blob/dd79e12a041aed8791a4ba9c8ec9a875075914d1/lib/gli/app.rb#L14-L32
