### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by nmeilick** [davetron5000/gli#72]
Hi,

are there any plans for i18n support?
Currently all output is hardcoded so I'm about to fork it for our internal projects. Of course if there's any interest, I'd be happy to submit our changes back for possible inclusion in your branch.

**Comment by davetron5000** [comment]
It's twelve years later so I didn't look into this. Closing as "won't fix" since I'd like to keep GLI stable. I doubt this would be a huge change, so if someone wants to tackle it, reach out with a PR.
