### ISSUE TITLE
per directory config file

### ISSUE THREAD

**Issue by martinciu** [davetron5000/gli#79]
if you specify config file as:

``` ruby
config_file '.awesomerc'
```

it should looked for the `.awesomerc` file in current directory and than in the users home directory.

When both files exists options should be merged and current directory options should have override home directory options.

**Comment by peter-ellis** [comment]
I found a hack that works nicely by overriding the [parse_config](https://github.com/davetron5000/gli/blob/gli-2/lib/gli/app_support.rb#L106-L115) method:

    module GLI
      module AppSupport

        def parse_config
          config = {
            "commands" => {}
          }

          # Build your config hash here by looping over multiple config files.

          return(config)
        end

      end
    end

**Comment by davetron5000** [comment]
Closing as old.  Note that #305 exists to capture all of `initconfig`'s failings.
