### ISSUE TITLE
Sub-sub-commands can not have a switch with the same name in gli-2.0.0-rc2.

### ISSUE THREAD

**Issue by bdiz** [davetron5000/gli#96]
This code raises exception.

```
        command :admin do |c|
            c.command :add do |c_add|
                c_add.flag :milestone
            end
            c.command :delete do |c_delete|
                c_delete.flag :milestone
            end
            c.command :misc do |c_misc|
                c_misc.switch :verbose
            end
        end
```

gli/dsl.rb:171:in `verify_unused_in_option': milestone has already been specified as a flag in the command admin (ArgumentError)
        from gli/dsl.rb:164:in`block in verify_unused'
        from gli/dsl.rb:163:in `each'
        from gli/dsl.rb:163:in`verify_unused'
        from gli/dsl.rb:65:in `flag'
        from gli/command_support.rb:42:in`flag'
        from gli/command_support.rb:40:in `flag'
        from options.rb:97:in`block (2 levels) in define_admin_commands'

**Comment by kowal** [comment]
Hi @davetron5000. If this issue is fixed then maybe https://github.com/davetron5000/gli/wiki/Subcommands#flags-and-switches section could be updated as well, what do you think?

**Comment by davetron5000** [comment]
It's been a long time since this issue was opened—do you want to take a stab at updating the wiki?

**Comment by kowal** [comment]
@davetron5000 can you please check if something like this would be fine : https://github.com/kowal/gli/wiki/Subcommands-updated.

Side question: How do we access parent-command options? I found that ``options[GLI::Command::PARENT]`` works but this isn't public API, right?

**Comment by davetron5000** [comment]
That seems ok—are you proposing changing the entire Subcommands page to that?  If not, go ahead and edit the GLI wiki directly.  I can look at the diff like that and we can tweak it as needed.

`GLI::Command::PARENT` is public—it's documented in the API docs, but probably not well documented elsewhere.

**Comment by kowal** [comment]
@davetron5000 I've updated `Flags and Switches` section. Also added new section 'Accessing parent command options'.

**Comment by davetron5000** [comment]
Awesome, thanks!  I tweaked it a bit, but this is much better than before

**Comment by kowal** [comment]
Cool, thanks!
